CREATE TABLE IF NOT EXISTS mobile_profiles (
  user_id INTEGER PRIMARY KEY REFERENCES mobile_users(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  age INTEGER NOT NULL DEFAULT 0,
  height INTEGER NOT NULL DEFAULT 0,
  education TEXT NOT NULL DEFAULT '',
  job TEXT NOT NULL DEFAULT '',
  income TEXT NOT NULL DEFAULT '',
  marriage TEXT NOT NULL DEFAULT '',
  intention TEXT NOT NULL DEFAULT '',
  bio TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS mobile_photos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES mobile_users(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mobile_likes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user_id INTEGER NOT NULL REFERENCES mobile_users(id) ON DELETE CASCADE,
  to_user_id INTEGER NOT NULL REFERENCES mobile_users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(from_user_id, to_user_id)
);

CREATE TABLE IF NOT EXISTS mobile_matches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_a_id INTEGER NOT NULL REFERENCES mobile_users(id) ON DELETE CASCADE,
  user_b_id INTEGER NOT NULL REFERENCES mobile_users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_a_id, user_b_id)
);

CREATE TABLE IF NOT EXISTS mobile_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id INTEGER NOT NULL REFERENCES mobile_matches(id) ON DELETE CASCADE,
  sender_id INTEGER NOT NULL REFERENCES mobile_users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO mobile_users(id, username, password, nickname) VALUES
  (2, '13900000001', '123456', '周然'),
  (3, '13900000002', '123456', '陈一鸣'),
  (4, '13900000003', '123456', '顾北'),
  (5, '13900000004', '123456', '沈亦')
ON CONFLICT (id) DO NOTHING;

INSERT INTO mobile_profiles(user_id, name, city, age, height, education, job, income, marriage, intention, bio) VALUES
  (1, '林晓', '上海', 29, 165, '本科', '产品经理', '20-30万', '未婚', '一年内结婚', '认真生活，也认真寻找可以一起过周末的人。'),
  (2, '周然', '上海', 31, 178, '硕士', '建筑设计师', '30-50万', '未婚', '认真婚恋', '喜欢展览、慢跑和做饭，希望关系里有稳定沟通。'),
  (3, '陈一鸣', '杭州', 32, 181, '本科', '软件工程师', '30-50万', '未婚', '稳定关系', '工作日写代码，周末骑行。想找一个能互相鼓励的人。'),
  (4, '顾北', '苏州', 30, 176, '硕士', '高校老师', '20-30万', '未婚', '一年内结婚', '安静但不无聊，重视家庭，也喜欢一起探索新地方。'),
  (5, '沈亦', '南京', 33, 180, '本科', '金融分析师', '50万以上', '未婚', '以结婚为前提', '作息规律，喜欢看书和羽毛球，希望彼此真诚坦荡。')
ON CONFLICT (user_id) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  age = EXCLUDED.age,
  height = EXCLUDED.height,
  education = EXCLUDED.education,
  job = EXCLUDED.job,
  income = EXCLUDED.income,
  marriage = EXCLUDED.marriage,
  intention = EXCLUDED.intention,
  bio = EXCLUDED.bio;

INSERT INTO mobile_photos(id, user_id, label, status) VALUES
  (1, 1, '生活照', 'approved'),
  (2, 1, '旅行照', 'pending'),
  (3, 2, '主页照片', 'approved'),
  (4, 3, '主页照片', 'approved'),
  (5, 4, '主页照片', 'pending'),
  (6, 5, '主页照片', 'approved')
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  label = EXCLUDED.label,
  status = EXCLUDED.status;

INSERT INTO mobile_likes(from_user_id, to_user_id) VALUES
  (2, 1),
  (4, 1)
ON CONFLICT (from_user_id, to_user_id) DO NOTHING;

INSERT INTO admin_menus(id, name, path, parent_id, type, permission) VALUES
  (20, 'dating', '/dating', 0, 'menu', ''),
  (21, 'dating:review', '', 20, 'button', 'dating:review')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  path = EXCLUDED.path,
  parent_id = EXCLUDED.parent_id,
  type = EXCLUDED.type,
  permission = EXCLUDED.permission;

UPDATE admin_roles
SET menu_ids = (
  SELECT jsonb_agg(DISTINCT value::int ORDER BY value::int)
  FROM jsonb_array_elements_text(admin_roles.menu_ids || '[20,21]'::jsonb) AS ids(value)
)
WHERE role_key = 'super_admin';

SELECT setval(pg_get_serial_sequence('mobile_users', 'id'), COALESCE((SELECT MAX(id) FROM mobile_users), 1));
SELECT setval(pg_get_serial_sequence('mobile_photos', 'id'), COALESCE((SELECT MAX(id) FROM mobile_photos), 1));
